In [2]:
import numpy as np 


######  Create a numpy array with filling random values, and shape of array 
######  should be (12,5), and pass this array from a user-defined function, and 
######  function should be able to return average, minimum, maximum, and 
######  no. of evens in your last row. 
######  For e.g. consider this is last row [41,52,63,96,85], 

In [3]:
a1 = np.arange(60).reshape(12,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [31]:

np.min(a1[-1])

55

In [17]:
np.max(a1[-1])

59

In [18]:
np.average(a1[-1])

57.0

In [8]:
a1[-1]

array([55, 56, 57, 58, 59])

In [29]:
lst_row = a1[-1, :]
no_even = np.sum(lst_row%2==0)
print(no_even)


2


 Let’s consider we have an array, e.g.
[[1 2 3 ],
[4 5 6 ],
[7 8 9 ]] 
And apply slicing techniques to get reversed order elements of all the rows, 
like this -> [[3 2 1],
 [6 5 4],
 [9 8 7]

In [28]:
a2      = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

reversed_array = a2[ :, ::-1]

print(reversed_array)


[[3 2 1]
 [6 5 4]
 [9 8 7]]
