In [1]:
#1. Given an array a = np.array([10, 20, 30, 40, 50]) and 
#    an index array i = np.array([0, 1, 3]), use fancy indexing 
#    to extract elements and assign new values to them. 

In [2]:
import numpy as np

# Given arrays
a = np.array([10, 20, 30, 40, 50])
i = np.array([0, 1, 3])

# Extract elements using fancy indexing
extracted_elements = a[i]
print("Extracted elements:", extracted_elements)

# Assign new values to the selected elements
new_values = np.array([100, 200, 400])
a[i] = new_values

print("Array after assignment:", a)


Extracted elements: [10 20 40]
Array after assignment: [100 200  30 400  50]


In [ ]:
#2.Create a 4x4 matrix and compute the sum of all elements, the sum 
#  of each column, and the sum of each row. 

In [3]:
# Create a 4x4 matrix
m = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# Step 2: Compute the sum of all elements
total_sum = np.sum(m)

# Step 3: Compute the sum of each column
column_sums = np.sum(m, axis=0)

# Step 4: Compute the sum of each row
row_sums = np.sum(m, axis=1)

# Print the results
print("Matrix:\n", m)
print("Sum of all elements:", total_sum)
print("Sum of each column:", column_sums)
print("Sum of each row:", row_sums)


Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Sum of all elements: 136
Sum of each column: [28 32 36 40]
Sum of each row: [10 26 42 58]


In [ ]:
#3. Given a 3-D array of shape (3, 4, 5), slice out a sub-array that
#   contains the last two rows and columns of the last two matrices.

In [4]:
#Create a 3-D array
array_3d = np.arange(60).reshape(3, 4, 5)
print("Original array:\n", array_3d)

#Slice out the sub-array containing the last two rows and columns of the last two matrices
sub_array = array_3d[:, -2:, -2:]
print("Sub-array with the last two rows and columns of the last two matrices:\n", sub_array)


Original array:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
Sub-array with the last two rows and columns of the last two matrices:
 [[[13 14]
  [18 19]]

 [[33 34]
  [38 39]]

 [[53 54]
  [58 59]]]
