In [1]:
  #Write a NumPy program to create an array of all even integers from 30 to 70.
# Question : Create a 3×3 numpy array of all True’s
# Question : Extract all odd numbers from array
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([1, 3, 5, 7, 9])
# Question: Replace all odd numbers in arr with -1
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# Question: Get the common items between a and b

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: array([2, 4])

In [2]:
#Write a NumPy program to create an array of all even integers from 30 to 70.
import numpy as np

# Create an array of all even integers from 30 to 70
even_integers = np.arange(30, 71, 2)
even_integers


array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [3]:
# Question : Create a 3×3 numpy array of all True’s
true_array = np.full((3, 3), True)
true_array


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
# Question : Extract all odd numbers from array
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([1, 3, 5, 7, 9])
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Extract all odd numbers
odd_numbers = arr[arr % 2 != 0]
odd_numbers


array([1, 3, 5, 7, 9])

In [5]:
# Question: Replace all odd numbers in arr with -1
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Replace all odd numbers with -1
arr[arr % 2 != 0] = -1
arr


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [6]:
# Question: Get the common items between a and b
# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])
# Output: array([2, 4])
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
# Get the common items between a and b
common_items = np.intersect1d(a, b)
common_items



array([2, 4])